import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { StoreProvider } from "@/store/StoreProvider";
import Auth from '@/components/auth';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <StoreProvider>
        <Navbar/>
        <body>{children}</body>
        <Footer/>
        <Auth/>
      </StoreProvider>
    </html>
  );
}
